##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## Snake
##

all	:
		@make -C ./Pacman
		@make -C ./Snake

clean	:
		@make clean -C ./Pacman
		@make clean -C ./Snake

fclean	:	clean
		@make fclean -C ./Pacman
		@make fclean -C ./Snake

re	:	fclean all

.PHONY	:	all clean fclean re
